In [4]:
import sys
!{sys.executable} -m pip install ipython-sql sqlalchemy mysql-connector-python

   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 2.1 MB/s eta 0:00:01
   ------------------- -------------------- 1.0/2.2 MB 2.2 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.2 MB 2.2 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.2 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 2.1 MB/s  0:00:01

   ---------------------------------------- 0/6 [ipython-genutils]
   ------ --------------------------------- 1/6 [sqlparse]
   ------ --------------------------------- 1/6 [sqlparse]
   ------ --------------------------------- 1/6 [sqlparse]
   ------------- -------------------------- 2/6 [prettytable]
   -------------------- ------------------- 3/6 [greenlet]
   -------------------- ------------------- 3/6 [greenlet]
   -------------------- ------------------- 3/6 [greenlet]
 

In [13]:
%load_ext sql
%sql mysql+mysqlconnector://root:02915678@localhost/sql_ex

The sql extension is already loaded. To reload it, use:
  %reload_ext sql


In [14]:
connection_string = "mysql+mysqlconnector://root:02915678@localhost/sql_ex"
%sql $connection_string

In [22]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

# 1. Компьютерная фирма
Схема БД состоит из четырех таблиц:

- Product(maker, model, type)
- PC(code, model, speed, ram, hd, cd, price)
- Laptop(code, model, speed, ram, hd, price, screen)
- Printer(code, model, color, type, price)

Таблица Product представляет производителя (maker), номер модели (model) и тип ('PC' - ПК, 'Laptop' - ПК-блокнот или 'Printer' - принтер). Предполагается, что номера моделей в таблице Product уникальны для всех производителей и типов продуктов.

 В таблице PC для каждого ПК, однозначно определяемого уникальным кодом – code, указаны модель – model (внешний ключ к таблице Product), скорость - speed (процессора в мегагерцах), объем памяти - ram (в мегабайтах), размер диска - hd (в гигабайтах), скорость считывающего устройства - cd (например, '4x') и цена - price (в долларах).

Таблица Laptop аналогична таблице РС за исключением того, что вместо скорости CD содержит размер экрана -screen (в дюймах). 

В таблице Printer для каждой модели принтера указывается, является ли он цветным - color ('y', если цветной), тип принтера - type (лазерный – 'Laser', струйный – 'Jet' или матричный – 'Matrix') и цена - price.

![computer database](image.png)

[create_database.sql](./../../databases/create_database.sql) - скрипт для создания ДБ

[computer_mysql_script.sql](./../../databases/computer_mysql_script.sql) - скрипт для создания "Компьютерная фирма"

### Задание: 1 (Serge I: 2002-09-30) [1]
Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd

In [25]:
%%sql
SELECT model, speed, hd
  FROM pc
 WHERE price < 500

 * mysql+mysqlconnector://root:***@localhost/sql_ex
4 rows affected.


model,speed,hd
1232,500,10.0
1232,450,8.0
1232,450,10.0
1260,500,10.0


### Задание: 2 (Serge I: 2002-09-21) [1]
Найдите производителей принтеров. Вывести: maker

In [26]:
%%sql
SELECT DISTINCT maker
  FROM Product
 WHERE type = 'Printer';

 * mysql+mysqlconnector://root:***@localhost/sql_ex
3 rows affected.


maker
A
D
E


### Задание: 3 (Serge I: 2002-09-30) [1]
Найдите номер модели, объем памяти и размеры экранов ноутбуков, цена которых превышает 1000 дол.

In [27]:
%%sql
SELECT model, ram, screen
  FROM Laptop
 WHERE price > 1000;

 * mysql+mysqlconnector://root:***@localhost/sql_ex
3 rows affected.


model,ram,screen
1750,128,14
1298,64,15
1752,128,14


### Задание: 4 (Serge I: 2002-09-21) [1]
Найдите все записи таблицы Printer для цветных принтеров.

In [29]:
%%sql
SELECT *
  FROM Printer
 WHERE color = 'y';


 * mysql+mysqlconnector://root:***@localhost/sql_ex
2 rows affected.


code,model,color,type,price
2,1433,y,Jet,270.00
3,1434,y,Jet,290.00


### Задание: 5 (Serge I: 2002-09-30) [1]
Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол.

In [32]:
%%sql
SELECT model, speed, hd
  FROM pc
 WHERE cd IN ('12x', '24x')
   AND price < 600;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
4 rows affected.


model,speed,hd
1232,500,10.0
1232,450,8.0
1232,450,10.0
1260,500,10.0


### Задание: 6 (Serge I: 2002-10-28) [2]
Для каждого производителя, выпускающего ноутбуки c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ноутбуков. Вывод: производитель, скорость.

In [34]:
%%sql
SELECT DISTINCT maker, speed
  FROM Product
  JOIN Laptop
    ON Product.model = Laptop.model
 WHERE type = 'Laptop'
   AND hd >= 10;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
4 rows affected.


maker,speed
B,750
A,600
A,750
A,450


### Задание: 7 (Serge I: 2002-11-02) [2]
Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).

In [36]:
%%sql
SELECT DISTINCT Product.model, price
  FROM pc
  JOIN Product
    ON Product.model = pc.model
 WHERE maker = 'B'

 UNION

SELECT DISTINCT Product.model, price
  FROM Laptop
  JOIN Product
    ON Product.model = Laptop.model
 WHERE maker = 'B'

 UNION

SELECT DISTINCT Product.model, price
  FROM Printer
  JOIN Product
    ON Product.model = Printer.model
 WHERE maker = 'B';


 * mysql+mysqlconnector://root:***@localhost/sql_ex
2 rows affected.


model,price
1121,850.00
1750,1200.00


### Задание: 8 (Serge I: 2003-02-03) [2]
Найдите производителя, выпускающего ПК, но не ноутбуки.

In [39]:
%%sql

SELECT maker
  FROM Product
 WHERE type = 'PC'

EXCEPT

SELECT maker
  FROM Product
 WHERE type = 'Laptop';


 * mysql+mysqlconnector://root:***@localhost/sql_ex
1 rows affected.


maker
E


### Задание: 9 (Serge I: 2002-11-02) [1]
Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker

In [40]:
%%sql
SELECT DISTINCT maker
  FROM Product
  JOIN pc
    ON Product.model = pc.model
 WHERE speed >= 450;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
3 rows affected.


maker
A
B
E


### Задание: 10 (Serge I: 2002-09-23) [1]
Найдите модели принтеров, имеющих самую высокую цену. Вывести: model, price

In [41]:
%%sql
SELECT model, price
  FROM Printer
 WHERE price = (SELECT MAX(price)
                  FROM Printer);


 * mysql+mysqlconnector://root:***@localhost/sql_ex
2 rows affected.


model,price
1276,400.00
1288,400.00


### Задание: 11 (Serge I: 2002-11-02) [1]
Найдите среднюю скорость ПК.

In [42]:
%%sql
SELECT AVG(speed)
  FROM pc;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
1 rows affected.


AVG(speed)
608.3333


### Задание: 12 (Serge I: 2002-11-02) [1]
Найдите среднюю скорость ноутбуков, цена которых превышает 1000 дол.


In [45]:
%%sql
SELECT AVG(speed)
  FROM Laptop
 WHERE price > 1000;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
1 rows affected.


AVG(speed)
700.0000


### Задание: 13 (Serge I: 2002-11-02) [1]
Найдите среднюю скорость ПК, выпущенных производителем A.

In [46]:
%%sql
SELECT AVG(speed)
  FROM pc
  JOIN Product
    ON pc.model = Product.model
 WHERE maker = 'A';


 * mysql+mysqlconnector://root:***@localhost/sql_ex
1 rows affected.


AVG(speed)
606.2500


### Задание: 15 (Serge I: 2003-02-03) [1]
Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD

In [47]:
%%sql
SELECT hd
  FROM pc
 GROUP BY hd
HAVING COUNT(hd) > 1;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
5 rows affected.


hd
5.0
14.0
8.0
20.0
10.0


### Задание: 16 (Serge I: 2003-02-03) [2]
Найдите пары моделей PC, имеющих одинаковые скорость и RAM. В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i), Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM.

In [48]:
%%sql
SELECT DISTINCT pc1.model, pc2.model, pc1.speed, pc1.ram
  FROM pc AS pc1
  JOIN pc AS pc2
    ON pc1.speed = pc2.speed
       AND pc1.ram = pc2.ram
 WHERE pc1.model > pc2.model;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
3 rows affected.


model,model_1,speed,ram
1233,1232,500,64
1233,1121,750,128
1260,1232,500,32


### Задание: 17 (Serge I: 2003-02-03) [2]
Найдите модели ноутбуков, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed


In [49]:
%%sql
SELECT DISTINCT 'Laptop' AS type, model, speed
  FROM Laptop
 WHERE speed < (SELECT MIN(speed)
                  FROM pc);


 * mysql+mysqlconnector://root:***@localhost/sql_ex
1 rows affected.


type,model,speed
Laptop,1298,350


### Задание: 18 (Serge I: 2003-02-03) [2]
Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price

In [50]:
%%sql
SELECT DISTINCT maker, price
  FROM Printer
  JOIN Product
    ON Printer.model = Product.model
 WHERE color = 'y'
   AND price =
       (SELECT MIN(price)
          FROM Printer
         WHERE color = 'y');


 * mysql+mysqlconnector://root:***@localhost/sql_ex
1 rows affected.


maker,price
D,270.00


### Задание: 19 (Serge I: 2003-02-13) [1]
Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ноутбуков.
Вывести: maker, средний размер экрана.

In [51]:
%%sql
SELECT maker, AVG(screen)
  FROM Product
  JOIN Laptop
    ON Product.model = Laptop.model
 GROUP BY maker;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
3 rows affected.


maker,AVG(screen)
A,13.0000
C,12.0000
B,14.0000


### Задание: 20 (Serge I: 2003-02-13) [2]
Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК.

In [52]:
%%sql
SELECT maker, COUNT(*)
  FROM Product
 WHERE type = 'PC'
 GROUP BY maker
HAVING COUNT(*) >= 3;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
1 rows affected.


maker,COUNT(*)
E,3


### Задание: 21 (Serge I: 2003-02-13) [1]
Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена.

In [53]:
%%sql
SELECT maker, MAX(price)
  FROM pc
  JOIN Product
    ON Product.model = pc.model
 GROUP BY maker;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
3 rows affected.


maker,MAX(price)
A,980.00
B,850.00
E,350.00


### Задание: 22 (Serge I: 2003-02-13) [1]
Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.

In [54]:
%%sql
SELECT speed, AVG(price)
  FROM pc
 WHERE speed > 600
 GROUP BY speed;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
3 rows affected.


speed,AVG(price)
750,900.000000
900,980.000000
800,970.000000


### Задание: 23 (Serge I: 2003-02-14) [2]
Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ноутбуки со скоростью не менее 750 МГц.

Вывести: Maker

In [55]:
%%sql
SELECT maker
  FROM Product
  JOIN pc
    ON Product.model = pc.model
 WHERE speed >= 750

INTERSECT

SELECT maker
  FROM Product
  JOIN Laptop
    ON Product.model = Laptop.model
 WHERE speed >= 750;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
2 rows affected.


maker
B
A


### Задание: 24 (Serge I: 2003-02-03) [2]
Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции.

In [56]:
%%sql
  WITH all_prices AS (
           SELECT model, price
             FROM pc

            UNION

           SELECT model, price
             FROM Laptop

            UNION

           SELECT model, price
             FROM Printer)
SELECT Product.model
  FROM Product
  JOIN all_prices
    ON Product.model = all_prices.model
 WHERE price = (SELECT MAX(price)
                  FROM all_prices);


 * mysql+mysqlconnector://root:***@localhost/sql_ex
1 rows affected.


model
1750


### Задание: 25 (Serge I: 2003-02-14) [2]
Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker

In [57]:
%%sql
     WITH PC_ram_table AS (
              SELECT maker
                FROM Product
                JOIN pc
                  ON pc.model = Product.model
               WHERE speed =
                     (SELECT MAX(speed)
                        FROM pc
                       WHERE ram = (SELECT MIN(ram)
                                      FROM pc))
                 AND ram = (SELECT MIN(ram)
                              FROM pc))
SELECT maker
  FROM Product
 WHERE type = 'Printer'

INTERSECT

SELECT *
  FROM PC_ram_table;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
2 rows affected.


maker
A
E


### Задание: 26 (Serge I: 2003-02-14) [2]
Найдите среднюю цену ПК и ноутбуков, выпущенных производителем A (латинская буква). Вывести: одна общая средняя цена.

In [58]:
%%sql
SELECT AVG(price)
  FROM (SELECT price
          FROM pc
          JOIN Product
            ON Product.model = pc.model
         WHERE maker = 'A'

         UNION ALL

        SELECT price
          FROM Laptop
          JOIN Product
            ON Product.model = Laptop.model
         WHERE maker = 'A') AS PC_Laptop_table;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
1 rows affected.


AVG(price)
754.166667


### Задание: 27 (Serge I: 2003-02-03) [2]
Найдите средний размер диска ПК каждого из тех производителей, которые выпускают и принтеры. Вывести: maker, средний размер HD.

In [59]:
%%sql
SELECT
	maker,
	AVG(hd)
FROM PC
JOIN Product ON PC.model = Product.model
WHERE maker IN (SELECT maker FROM Product WHERE type = 'Printer')
GROUP BY maker

 * mysql+mysqlconnector://root:***@localhost/sql_ex
2 rows affected.


maker,AVG(hd)
A,14.75
E,10.0


### Задание: 28 (Serge I: 2012-05-04) [1]
Используя таблицу Product, определить количество производителей, выпускающих по одной модели.

In [60]:
%%sql
SELECT
	COUNT(*)
FROM (
	SELECT
		maker
	FROM Product
	GROUP BY maker
	HAVING COUNT(model) = 1
) as maker_one_model_count

 * mysql+mysqlconnector://root:***@localhost/sql_ex
1 rows affected.


COUNT(*)
1


### Задание: 97 (qwrqwr: 2013-02-15) [2]
Отобрать из таблицы Laptop те строки, для которых выполняется следующее условие:
значения из столбцов speed, ram, price, screen возможно расположить таким образом, что каждое последующее значение будет превосходить предыдущее в 2 раза или более.
Замечание: все известные характеристики ноутбуков больше нуля.
Вывод: code, speed, ram, price, screen.


In [61]:
%%sql
  WITH values_table AS (
    -- Эта таблица объединяет все значения как value, а также сохраняет их code
           SELECT speed AS value, code, 'speed' AS type
             FROM Laptop

            UNION ALL

           SELECT ram, code, 'ram'
             FROM Laptop

            UNION ALL

           SELECT price, code, 'price'
             FROM Laptop

            UNION ALL

           SELECT screen, code, 'screen'
             FROM Laptop)
SELECT Laptop.code, speed, ram, price, screen
  FROM Laptop
  -- Таблица, которая выводит необходимые code
  JOIN (SELECT DISTINCT code
          -- Таблица с оконной функцией, которая сравнивает текущую value и предыдущую
          FROM (SELECT value,
                       code,
                       -- Оконная функция, которая сравнивает текущее значение с его предыдущим. Делит их
			           -- По условию, нам нужно >= 2
                       value/COALESCE(LAG(value) OVER (PARTITION BY code ORDER BY value), 0.1) AS `div`
                  FROM values_table) AS lag_table
         WHERE `div` >= 2
         GROUP BY code
         -- Так как нам нужно, чтобы все значения определенного code соответствовали, то их кол-во должно быть 4
        HAVING COUNT(code) = 4) AS code_table
    ON code_table.code = Laptop.code;


 * mysql+mysqlconnector://root:***@localhost/sql_ex
2 rows affected.


code,speed,ram,price,screen
1,350,32,700.00,11
6,450,64,950.00,12
