name: Update nested README

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install markdown-autodocs
        run: npm install --global markdown-autodocs

      - name: Update README
        run: |
          markdown-autodocs \
            -c code-block \
            -o "./README.md" \
            -o "./select-training/computer-firm/README.md"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes"
          else
            git add "./select-training/computer-firm/README.md"
            git add "./README.md"
            git commit -m "docs: update SQL README"
            git push
          fi